name: Deploy to Dokku

on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - id: deploy
        name: Deploy to dokku
        uses: ochaplashkin/dokku-deploy-github-action@master
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.DOKKU_HOST }}
            app-name: smoke-test
            git-push-flags: '--force'
